### ISSUE TITLE
Bug: "randomgu" instead of "randomngu" in __init__.py

### ISSUE THREAD

**Issue by wrjones104** [Rosalie-A/Archipelago#26]
### What happened?

Line 120
                if character_list[character] == "randomgu":
should be
                if character_list[character] == "randomngu":

breaking generation as-is

### What were the expected results?

Generation completes successfully with change

### Software

Local generation

**Comment by Javinat0r** [comment]
Submitted PR #28 
https://github.com/Rosalie-A/Archipelago/pull/28

**Comment by Javinat0r** [comment]
PR #28 merged. Suggest closing this issue @wrjones104 .
