### ISSUE TITLE
Bug: Generation issue with super metroid world

### ISSUE THREAD

**Issue by Javinat0r** [Rosalie-A/Archipelago#33]
### What happened?

Can't generate a game locally without deleting the /worlds/sm folder. Seems to be a bad interaction between Utils.py files between worlds/sm and worlds/ff6wc . Beyond my knowledge, but I believe a known and reported issue in the past. Mainly adding this report for tracking purposes.

### What were the expected results?

Able to generate games without deleting the SM world.

### Software

Local generation

**Comment by Javinat0r** [comment]
```C:\Users\uncle\AppData\Local\Programs\Python\Python310\python.exe C:\Users\uncle\PycharmProjects\Archipelago\Generate.py 
Traceback (most recent call last):
  File "C:\Users\uncle\PycharmProjects\Archipelago\Generate.py", line 18, in <module>
    from worlds.alttp import Options as LttPOptions
  File "C:\Users\uncle\PycharmProjects\Archipelago\worlds\__init__.py", line 70, in <module>
    importlib.import_module(f".{world_source.path}", "worlds")
  File "C:\Users\uncle\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\uncle\PycharmProjects\Archipelago\worlds\sm\__init__.py", line 10, in <module>
    from worlds.sm.variaRandomizer.graph.graph_utils import GraphUtils
  File "C:\Users\uncle\PycharmProjects\Archipelago\worlds\sm\variaRandomizer\graph\graph_utils.py", line 4, in <module>
    from utils.parameters import Knows
ModuleNotFoundError: No module named 'utils.parameters'

Process finished with exit code 1
```

**Comment by Javinat0r** [comment]
Issue may be fixed by @lordlou pull request on main AP repo here: https://github.com/ArchipelagoMW/Archipelago/pull/1584

**Comment by Javinat0r** [comment]
Note that the above PR was accepted and added to the main branch last week. Issue may be fixed when changes are merged into this fork.

**Comment by Rosalie-A** [comment]
I finally got off my lazy ass and updated the branch. This is an intermittent problem anyway (I've run into it and fixed it by recloning the repo, and I couldn't tell you why that worked) that's caused by another world's coding, so I can't and won't do anything about it if it's still around: Super Metroid's problems are SM's to solve.
